version: '2'

services:
  webapp:
    build: ./webapp
    image: webapp:0.0.1
    restart: always
    ports:
      - "8080:8080"
    depends_on: 
      - mongodb
    networks:
      wpnetwork:
        aliases:
          - webapp

  # NOTE: check webapp/src/config/config.js => mongodb connection to alias, resolves to docker internal ip address
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./mongodb/data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --noauth --bind_ip=0.0.0.0 --smallfiles --oplogSize 128
    networks:
      wpnetwork:
        aliases:
          - webapp

networks:
  wpnetwork:
    driver: bridge