version: '2'
services:
    mongodb:
        image: mongo:latest
        restart: unless-stopped
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --noauth --bind_ip=0.0.0.0 --smallfiles --oplogSize 128
